services:
  - type: web
    name: gbtnetwork-node1
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: BOOTNODE_URL
        value: https://gbtnetwork-bootnode.onrender.com/static-nodes.json
      - key: REFRESH_INTERVAL
        value: "300"
